# Generated by Django 2.2.1 on 2020-09-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=1000)),
                ('payment_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('E', 'Else')], default='Y', max_length=1)),
                ('slug', models.SlugField(blank=True, max_length=2000, null=True)),
                ('ticket_type', models.CharField(blank=True, choices=[('Q', 'Question'), ('P', 'Problem'), ('T', 'Task')], max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('U', 'Urgent')], default='L', max_length=20)),
            ],
        ),
    ]
