# Generated by Django 2.2.1 on 2020-10-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20200929_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ticket.Ticket'),
        ),
    ]
